</body>
<script>
	(function($){
		$(window).load(function(){
			$(".scroll_set_1").mCustomScrollbar({
				scrollButtons:{enable:true},
				theme:"light-thick",
				scrollbarPosition:"outside"
			});
		});
	})(jQuery);
</script>
</html>
