INSERT INTO "items"
("name", "slug")
VALUES
('S&TC', 'sys-stc'),
('PSD', 'sys-psd'),
('APG', 'sys-apg'),
('ICSS', 'sys-icss'),
('CMMS', 'sys-cmms'),
('ET', 'sys-et'),
('TW', 'sys-tw'),
('COMMS', 'sys-comms'),
('AFC', 'sys-afc'),
('PSDS', 'sys-psds'),
('DEMV', 'sys-demv'),
('PSDS R1', 'sys-psds-r1'),
('PSDS R2', 'sys-psds-r2'),
('PSDS R3', 'sys-psds-r3'),
('PSDS R4', 'sys-psds-r4'),
('PSDS R5', 'sys-psds-r5'),
('PSDS R6', 'sys-psds-r6'),
('PSDS R7', 'sys-psds-r7'),
('TW KD8', 'sys-tw-kd8'),
('TW KD9A', 'sys-tw-kd9a'),
('TW KD9', 'sys-tw-kd9'),
('TW KD10', 'sys-tw-kd10'),
('TW KD11', 'sys-tw-kd11'),
('TW KD11A', 'sys-tw-kd11a'),
('TW KD12', 'sys-tw-kd12'),
('TW KD13', 'sys-tw-kd13'),
('TW KD14', 'sys-tw-kd14'),
('TW KD15', 'sys-tw-kd15'),
('TW KD16', 'sys-tw-kd16');