INSERT INTO "meta_group"
("name")
VALUES
('System - Automatic Fare Collection'),
('System - Automatic Platform Gate'),
('System - Computerised Maintenance Management System'),
('System - Communications, GIRN & IDS'),
('System - Depot Equipment & Maintenance Vehicle / Works Train'),
('System - Electric Train'),
('System - Integrated Control Supervisory System'),
('System - Platform Screen Door'),
('System - Power Supply & Distribution System'),
('System - Power Supply & Distribution System - R1'),
('System - Power Supply & Distribution System - R2'),
('System - Power Supply & Distribution System - R3'),
('System - Power Supply & Distribution System - R4'),
('System - Power Supply & Distribution System - R5'),
('System - Power Supply & Distribution System - R6'),
('System - Power Supply & Distribution System - R7'),
('System - Signalling & Train Control'),
('System - Trackworks'),
('System - Trackworks - KD10'),
('System - Trackworks - KD11'),
('System - Trackworks - KD11A'),
('System - Trackworks - KD12'),
('System - Trackworks - KD13'),
('System - Trackworks - KD14'),
('System - Trackworks - KD15'),
('System - Trackworks - KD16'),
('System - Trackworks - KD8'),
('System - Trackworks - KD9'),
('System - Trackworks - KD9A');